[workspace]
authors = ["Brandon Monier <bm646@cornell.edu>"]
channels = ["conda-forge"]
name = "imp"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.0.1"

[tasks]
imp     = "python src/imp.py"
impstat = "python src/imp_static.py"

[dependencies]
python = "3.10.*"
numpy = ">=2.2.6,<3"
pandas = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
d3blocks = ">=1.6.1, <2"
